name: build games
on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
    paths:
      - games/**
jobs:
  push:
    name: "games:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - rust
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./games/${{ matrix.game }}
          file: ./games/${{ matrix.game }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/kaijurust/games-node:${{ matrix.game }}
